# Generated by Django 4.0.6 on 2022-07-18 07:48

import abror_marketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSmmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('body1', models.TextField(blank=True, null=True)),
                ('body2', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=abror_marketing.models.upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.URLField(blank=True, max_length=255, null=True, verbose_name='Link')),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogoRoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('body1', models.TextField(blank=True, null=True)),
                ('body2', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=abror_marketing.models.upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='OurProjectsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('body1', models.TextField(blank=True, null=True)),
                ('body2', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=abror_marketing.models.upload_location)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=abror_marketing.models.upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='TargetingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('body1', models.TextField(blank=True, null=True)),
                ('body2', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=abror_marketing.models.upload_location)),
            ],
        ),
    ]
