# Generated by Django 4.0.6 on 2022-07-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abror_marketing', '0002_carouselmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
