# Generated by Django 4.0.6 on 2022-07-19 02:12

import abror_marketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abror_marketing', '0003_alter_contactmodel_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssmmmodel',
            name='body1_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesssmmmodel',
            name='body1_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesssmmmodel',
            name='body1_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesssmmmodel',
            name='body2_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesssmmmodel',
            name='body2_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesssmmmodel',
            name='body2_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesssmmmodel',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to=abror_marketing.models.upload_location),
        ),
        migrations.AddField(
            model_name='businesssmmmodel',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to=abror_marketing.models.upload_location),
        ),
        migrations.AddField(
            model_name='businesssmmmodel',
            name='image_uz',
            field=models.ImageField(blank=True, null=True, upload_to=abror_marketing.models.upload_location),
        ),
        migrations.AddField(
            model_name='businesssmmmodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businesssmmmodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businesssmmmodel',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logorolemodel',
            name='body1_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logorolemodel',
            name='body1_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logorolemodel',
            name='body1_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logorolemodel',
            name='body2_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logorolemodel',
            name='body2_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logorolemodel',
            name='body2_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logorolemodel',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to=abror_marketing.models.upload_location),
        ),
        migrations.AddField(
            model_name='logorolemodel',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to=abror_marketing.models.upload_location),
        ),
        migrations.AddField(
            model_name='logorolemodel',
            name='image_uz',
            field=models.ImageField(blank=True, null=True, upload_to=abror_marketing.models.upload_location),
        ),
        migrations.AddField(
            model_name='logorolemodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logorolemodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logorolemodel',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourprojectsmodel',
            name='body1_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourprojectsmodel',
            name='body1_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourprojectsmodel',
            name='body1_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourprojectsmodel',
            name='body2_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourprojectsmodel',
            name='body2_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourprojectsmodel',
            name='body2_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourprojectsmodel',
            name='image1_en',
            field=models.ImageField(blank=True, null=True, upload_to=abror_marketing.models.upload_location),
        ),
        migrations.AddField(
            model_name='ourprojectsmodel',
            name='image1_ru',
            field=models.ImageField(blank=True, null=True, upload_to=abror_marketing.models.upload_location),
        ),
        migrations.AddField(
            model_name='ourprojectsmodel',
            name='image1_uz',
            field=models.ImageField(blank=True, null=True, upload_to=abror_marketing.models.upload_location),
        ),
        migrations.AddField(
            model_name='ourprojectsmodel',
            name='image2_en',
            field=models.ImageField(blank=True, null=True, upload_to=abror_marketing.models.upload_location),
        ),
        migrations.AddField(
            model_name='ourprojectsmodel',
            name='image2_ru',
            field=models.ImageField(blank=True, null=True, upload_to=abror_marketing.models.upload_location),
        ),
        migrations.AddField(
            model_name='ourprojectsmodel',
            name='image2_uz',
            field=models.ImageField(blank=True, null=True, upload_to=abror_marketing.models.upload_location),
        ),
        migrations.AddField(
            model_name='ourprojectsmodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourprojectsmodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourprojectsmodel',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='targetingmodel',
            name='body1_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetingmodel',
            name='body1_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetingmodel',
            name='body1_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetingmodel',
            name='body2_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetingmodel',
            name='body2_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetingmodel',
            name='body2_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetingmodel',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to=abror_marketing.models.upload_location),
        ),
        migrations.AddField(
            model_name='targetingmodel',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to=abror_marketing.models.upload_location),
        ),
        migrations.AddField(
            model_name='targetingmodel',
            name='image_uz',
            field=models.ImageField(blank=True, null=True, upload_to=abror_marketing.models.upload_location),
        ),
        migrations.AddField(
            model_name='targetingmodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='targetingmodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='targetingmodel',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
