# Generated by Django 4.0.6 on 2022-07-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abror_marketing', '0005_categoriesmodels_businesssmmmodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesmodels',
            name='title_en',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='categoriesmodels',
            name='title_ru',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='categoriesmodels',
            name='title_uz',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
