# Generated by Django 4.0.6 on 2022-07-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abror_marketing', '0006_categoriesmodels_title_en_categoriesmodels_title_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriesmodels',
            old_name='title',
            new_name='title1',
        ),
        migrations.RenameField(
            model_name='categoriesmodels',
            old_name='title_en',
            new_name='title1_en',
        ),
        migrations.RenameField(
            model_name='categoriesmodels',
            old_name='title_ru',
            new_name='title1_ru',
        ),
        migrations.RenameField(
            model_name='categoriesmodels',
            old_name='title_uz',
            new_name='title1_uz',
        ),
        migrations.AddField(
            model_name='categoriesmodels',
            name='title2',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoriesmodels',
            name='title2_en',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='categoriesmodels',
            name='title2_ru',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='categoriesmodels',
            name='title2_uz',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='categoriesmodels',
            name='title3',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoriesmodels',
            name='title3_en',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='categoriesmodels',
            name='title3_ru',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='categoriesmodels',
            name='title3_uz',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='categoriesmodels',
            name='title4',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
