# Generated by Django 4.0.6 on 2022-07-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abror_marketing', '0008_categoriesmodels_title4_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesssmmmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ourprojectsmodel',
            name='category',
        ),
    ]
