# Generated by Django 4.0.6 on 2022-07-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abror_marketing', '0009_remove_businesssmmmodel_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service1', models.CharField(max_length=55)),
                ('service1_ru', models.CharField(max_length=55, null=True)),
                ('service1_en', models.CharField(max_length=55, null=True)),
                ('service1_uz', models.CharField(max_length=55, null=True)),
                ('service2', models.CharField(max_length=55)),
                ('service2_ru', models.CharField(max_length=55, null=True)),
                ('service2_en', models.CharField(max_length=55, null=True)),
                ('service2_uz', models.CharField(max_length=55, null=True)),
                ('service3', models.CharField(max_length=55)),
                ('service3_ru', models.CharField(max_length=55, null=True)),
                ('service3_en', models.CharField(max_length=55, null=True)),
                ('service3_uz', models.CharField(max_length=55, null=True)),
                ('service4', models.CharField(max_length=55)),
                ('service4_ru', models.CharField(max_length=55, null=True)),
                ('service4_en', models.CharField(max_length=55, null=True)),
                ('service4_uz', models.CharField(max_length=55, null=True)),
                ('service5', models.CharField(max_length=55)),
                ('service5_ru', models.CharField(max_length=55, null=True)),
                ('service5_en', models.CharField(max_length=55, null=True)),
                ('service5_uz', models.CharField(max_length=55, null=True)),
                ('service6', models.CharField(max_length=55)),
                ('service6_ru', models.CharField(max_length=55, null=True)),
                ('service6_en', models.CharField(max_length=55, null=True)),
                ('service6_uz', models.CharField(max_length=55, null=True)),
            ],
        ),
    ]
