# Generated by Django 4.0.6 on 2022-07-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abror_marketing', '0010_servicesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmodel',
            name='service7',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='service7_en',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='service7_ru',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='service7_uz',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
