# Generated by Django 4.0.6 on 2022-07-23 21:36

import abror_marketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abror_marketing', '0011_servicesmodel_service7_servicesmodel_service7_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainLogoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=abror_marketing.models.upload_location)),
                ('image_ru', models.ImageField(blank=True, null=True, upload_to=abror_marketing.models.upload_location)),
                ('image_en', models.ImageField(blank=True, null=True, upload_to=abror_marketing.models.upload_location)),
                ('image_uz', models.ImageField(blank=True, null=True, upload_to=abror_marketing.models.upload_location)),
            ],
        ),
    ]
